In [130]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.cluster import KMeans

#Tutorial can be found here: https://www.youtube.com/watch?v=CIfZi0niNE0

In [131]:
dataset = pd.read_csv('CoffeeBeansCleaned.csv')

In [132]:
X = dataset

In [133]:
ct = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[-14,-13,-12])], remainder="passthrough")

In [134]:
X_train = np.array(ct.fit_transform(X))

In [135]:
#Clustering
km = KMeans(n_clusters = 3, init="k-means++", random_state=42)
y_means = km.fit(X_train)

In [136]:
y_means

KMeans(n_clusters=3, random_state=42)

In [137]:
#Centers
y_means.cluster_centers_

array([[3.80952381e-01, 3.57142857e-01, 2.61904762e-01, 4.04761905e-01,
        5.71428571e-01, 2.38095238e-02, 3.33333333e-01, 2.38095238e-01,
        1.42857143e-01, 1.19047619e-01, 9.52380952e-02, 7.14285714e-02,
        7.16071429e+00, 7.05357143e+00, 6.97023810e+00, 7.07142857e+00,
        6.97023810e+00, 1.00000000e+01, 7.00595238e+00, 1.00000000e+01,
        1.00000000e+01, 7.10714286e+00, 7.93392857e+01],
       [4.48275862e-01, 3.79310345e-01, 1.72413793e-01, 6.89655172e-01,
        2.93103448e-01, 1.72413793e-02, 1.89655172e-01, 1.37931034e-01,
        3.62068966e-01, 1.72413793e-01, 8.62068966e-02, 5.17241379e-02,
        6.81896552e+00, 6.56034483e+00, 6.42672414e+00, 6.38362069e+00,
        6.35344828e+00, 1.00000000e+01, 6.41810345e+00, 1.00000000e+01,
        1.00000000e+01, 6.43534483e+00, 7.53706897e+01],
       [2.68292683e-01, 3.04878049e-01, 4.26829268e-01, 7.07317073e-01,
        2.07317073e-01, 8.53658537e-02, 1.82926829e-01, 7.31707317e-02,
        1.21951220e-01

In [138]:
#Check where each record resides in which cluster
km.labels_

array([2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 0, 2, 1, 1, 0, 0, 0, 2, 0,
       2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 0, 1, 1,
       0, 1, 1, 1, 2, 0, 0, 2, 1, 2, 2, 1, 2, 0, 0, 2, 0, 0, 2, 1, 0, 0,
       2, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2,
       0, 1, 2, 0, 0, 1, 0, 2, 1, 2, 2, 2, 1, 2, 0, 0, 2, 1, 2, 2, 2, 2,
       1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 0, 1,
       2, 2, 2, 2, 2, 2])

In [139]:
#Count how many records are in each of the clusters
labels = km.labels_

clusterCount = np.bincount(labels)
clusterCount

array([42, 58, 82], dtype=int64)

In [145]:
#List the records in dataframe form

df_with_cluster_column = pd.read_csv('CoffeeBeansCleaned.csv')

cluster = km.labels_
df_with_cluster_column['cluster'] = cluster

df_with_cluster_column

Variety Shape  Sieve  Aroma  Flavor  Aftertaste  Acidity  Body  \
0        CO    PE     13   6.50    6.00        6.00     6.00  6.00   
1        CO    PE     13   6.00    6.00        6.00     6.00  6.00   
2        CO    PE     13   6.75    6.00        6.00     6.00  6.00   
3        CO    PE     13   6.75    6.50        6.50     6.00  6.00   
4        CO    MI     13   6.75    6.25        6.25     6.25  6.50   
..      ...   ...    ...    ...     ...         ...      ...   ...   
177      OA    FL     18   6.50    6.00        6.00     6.00  6.25   
178      OA    FL     18   6.00    6.00        6.00     6.00  6.00   
179      OA    FL     18   6.00    6.00        6.00     6.00  6.00   
180      OA    FL     18   6.25    6.25        6.25     6.00  6.25   
181      OA    FL     18   6.25    6.25        6.25     6.25  6.25   

     Uniformity  Balance  clean cup  Sweetness  Taster score  Final score  \
0            10     6.00         10         10          6.00        72.50   
1            10     6.00         10         10          6.00        72.00   
2            10     6.00         10         10          6.00        72.75   
3            10     6.00         10         10          6.00        73.75   
4            10     6.50         10         10          6.50        75.00   
..          ...      ...        ...        ...           ...          ...   
177          10     6.00         10         10          6.00        72.75   
178          10     6.00         10         10          6.25        72.25   
179          10     6.00         10         10          6.50        72.50   
180          10     6.00         10         10          6.25        73.25   
181          10     6.25         10         10          6.25        73.75   

     cluster  
0          2  
1          2  
2          2  
3          2  
4          1  
..       ...  
177        2  
178        2  
179        2  
180        2  
181        2  

[182 rows x 15 columns]

In [177]:
#List the elements of cluster n method
def display(fullList, clusternum):
    new_list = []
    for x in list_with_clusters:
        for y in x:
            if x[14] == clusternum:
                new_list.append(x)
                break
    unique_df = pd.DataFrame(new_list)
    return unique_df

In [178]:
list_with_clusters = df_with_cluster_column.values.tolist()

#List elements of cluster 0
df_n = display(list_with_clusters, 0)
df_n

0   1   2     3     4     5     6     7   8     9   10  11    12     13  \
0   CO  MI  14  7.00  7.00  7.25  7.25  7.00  10  7.00  10  10  7.25  79.75   
1   CO  MI  14  7.75  7.25  7.25  7.25  7.00  10  7.00  10  10  7.25  80.75   
2   CO  MI  14  7.50  7.00  7.00  7.00  6.50  10  7.25  10  10  7.25  79.50   
3   CO  MI  15  7.00  7.00  7.00  6.75  7.00  10  6.75  10  10  6.75  78.25   
4   CO  MI  15  7.25  7.25  7.00  7.00  6.75  10  7.25  10  10  7.00  79.50   
5   CO  FL  13  7.00  7.00  7.00  7.25  7.00  10  7.00  10  10  7.00  79.25   
6   CO  FL  13  7.50  7.25  7.50  7.25  7.25  10  7.25  10  10  7.25  81.25   
7   CO  FL  13  7.00  7.00  7.00  7.00  6.50  10  7.00  10  10  7.00  78.50   
8   CO  FL  16  7.00  7.25  7.25  7.25  7.25  10  7.25  10  10  7.50  80.75   
9   CO  FL  16  7.25  7.25  6.75  7.00  7.00  10  6.50  10  10  6.75  78.50   
10  CO  FL  16  7.00  6.75  6.25  7.00  6.50  10  6.75  10  10  7.25  77.50   
11  CO  FL  16  7.50  7.75  7.00  7.00  7.00  10  7.00  10  10  7.00  80.25   
12  CO  FL  17  7.50  7.25  7.50  7.50  7.00  10  7.25  10  10  7.25  81.25   
13  CO  FL  17  7.50  7.25  7.25  7.25  7.25  10  7.25  10  10  7.25  81.00   
14  CO  FL  18  7.00  7.25  7.00  7.75  7.25  10  7.00  10  10  7.25  80.50   
15  CO  FL  18  7.00  7.00  7.00  7.25  7.00  10  7.00  10  10  7.25  79.50   
16  CR  MI  13  7.00  7.25  7.25  7.25  7.25  10  7.25  10  10  7.25  80.50   
17  CR  MI  13  6.75  6.75  6.75  6.75  6.75  10  6.75  10  10  7.00  77.50   
18  CR  MI  13  7.25  7.50  7.50  7.00  7.00  10  7.25  10  10  7.25  80.75   
19  CR  MI  13  7.50  7.25  6.25  6.25  6.50  10  7.00  10  10  7.00  77.75   
20  CR  MI  13  6.50  7.00  7.00  6.75  6.75  10  6.75  10  10  7.00  77.75   
21  CR  MI  14  7.25  7.00  7.00  7.25  7.25  10  7.00  10  10  7.00  79.75   
22  CR  MI  14  7.00  7.25  7.25  7.25  7.00  10  7.25  10  10  7.25  80.25   
23  CR  MI  14  7.00  7.25  7.00  7.25  7.25  10  7.25  10  10  7.50  80.50   
24  CR  MI  14  7.75  7.00  6.50  6.75  6.50  10  7.00  10  10  7.00  78.50   
25  CR  MI  14  7.00  7.00  7.25  7.25  7.25  10  7.00  10  10  7.00  79.75   
26  CR  MI  14  7.00  6.75  6.75  6.50  7.00  10  6.50  10  10  7.00  77.50   
27  CR  MI  15  7.25  7.00  7.00  7.00  6.50  10  7.00  10  10  7.00  78.75   
28  CR  MI  15  7.50  7.00  7.00  7.25  7.00  10  7.00  10  10  7.00  79.75   
29  CR  MI  15  7.25  6.50  6.50  7.00  6.25  10  7.00  10  10  7.00  77.50   
30  CR  MI  15  7.50  7.00  7.00  7.00  7.00  10  7.00  10  10  7.00  79.50   
31  OA  PE  13  7.00  7.00  7.00  7.00  7.00  10  7.00  10  10  7.00  79.00   
32  OA  MI  13  7.00  7.25  6.75  7.25  7.25  10  7.00  10  10  7.50  80.00   
33  OA  MI  13  7.00  7.00  7.00  7.25  7.00  10  7.00  10  10  7.00  79.25   
34  OA  MI  13  7.00  6.50  6.50  6.50  7.00  10  7.00  10  10  7.00  77.50   
35  OA  MI  14  7.00  7.00  7.00  7.25  7.25  10  7.00  10  10  7.25  79.75   
36  OA  FL  13  7.00  7.00  7.00  7.25  7.25  10  7.00  10  10  7.25  79.75   
37  OA  FL  13  7.25  6.50  6.50  7.25  7.25  10  6.75  10  10  7.00  78.50   
38  OA  FL  16  7.00  7.00  7.00  7.00  7.00  10  7.00  10  10  7.00  79.00   
39  OA  FL  17  7.00  7.00  7.00  7.00  7.00  10  7.00  10  10  7.00  79.00   
40  OA  FL  17  7.00  7.00  7.00  7.00  7.00  10  7.00  10  10  7.00  79.00   
41  OA  FL  18  7.25  7.00  7.00  7.00  7.25  10  7.00  10  10  7.00  79.50   

    14  
0    0  
1    0  
2    0  
3    0  
4    0  
5    0  
6    0  
7    0  
8    0  
9    0  
10   0  
11   0  
12   0  
13   0  
14   0  
15   0  
16   0  
17   0  
18   0  
19   0  
20   0  
21   0  
22   0  
23   0  
24   0  
25   0  
26   0  
27   0  
28   0  
29   0  
30   0  
31   0  
32   0  
33   0  
34   0  
35   0  
36   0  
37   0  
38   0  
39   0  
40   0  
41   0

In [179]:
#List elements of cluster 1
df_nplus1 = display(list_with_clusters, 1)
df_nplus1

0   1   2     3     4     5     6     7   8     9   10  11    12     13  \
0   CO  MI  13  6.75  6.25  6.25  6.25  6.50  10  6.50  10  10  6.50  75.00   
1   CO  MI  13  6.50  6.50  6.25  6.25  6.50  10  6.75  10  10  6.75  75.50   
2   CO  MI  13  7.50  6.50  6.75  6.50  6.50  10  6.50  10  10  6.50  76.75   
3   CO  MI  14  6.50  6.25  6.00  6.00  6.50  10  6.50  10  10  6.50  74.25   
4   CO  MI  14  7.00  6.25  6.00  6.50  6.25  10  6.25  10  10  6.25  74.50   
5   CO  MI  14  7.00  6.50  6.50  6.50  6.25  10  6.50  10  10  6.25  75.50   
6   CO  FL  13  6.75  6.75  6.50  6.50  6.50  10  6.75  10  10  6.75  76.50   
7   CO  FL  13  7.25  6.50  6.50  7.00  6.75  10  6.50  10  10  6.50  77.00   
8   CO  FL  13  7.25  6.50  6.50  7.00  6.75  10  6.50  10  10  6.50  77.00   
9   CO  FL  14  6.75  6.75  6.75  6.50  6.50  10  6.50  10  10  6.50  76.25   
10  CO  FL  14  6.75  6.75  6.75  6.75  6.00  10  6.00  10  10  6.50  75.50   
11  CO  FL  15  6.50  6.50  6.25  6.25  6.25  10  6.25  10  10  6.25  74.25   
12  CO  FL  15  6.50  6.50  6.25  6.25  6.25  10  6.25  10  10  6.25  74.25   
13  CO  FL  15  7.00  7.00  7.00  6.00  6.00  10  6.50  10  10  6.50  75.50   
14  CO  FL  15  6.50  6.75  6.25  6.25  6.25  10  6.25  10  10  6.50  74.75   
15  CO  FL  15  6.75  6.50  6.00  6.00  6.50  10  6.50  10  10  6.50  74.75   
16  CO  FL  15  6.75  6.50  6.25  6.00  6.00  10  6.50  10  10  6.50  74.50   
17  CO  FL  15  6.75  6.25  6.25  6.75  6.00  10  6.25  10  10  6.50  74.75   
18  CO  FL  16  7.00  6.75  6.75  6.50  6.25  10  6.50  10  10  6.25  76.00   
19  CO  FL  16  7.00  6.50  6.25  6.25  6.25  10  6.25  10  10  6.25  74.75   
20  CO  FL  16  6.50  6.50  6.50  6.25  6.25  10  6.50  10  10  7.00  75.50   
21  CO  FL  16  6.50  6.50  6.50  6.25  6.25  10  6.50  10  10  6.50  75.00   
22  CO  FL  16  6.50  6.50  6.50  6.75  6.50  10  6.50  10  10  7.00  76.25   
23  CO  FL  16  7.50  6.25  6.00  6.00  6.25  10  6.25  10  10  6.25  74.50   
24  CO  FL  17  7.25  6.75  6.75  6.50  6.25  10  6.50  10  10  6.50  76.50   
25  CO  FL  18  7.25  6.25  6.00  6.25  6.00  10  6.25  10  10  6.25  74.25   
26  CR  MI  13  7.25  6.25  6.25  6.00  6.50  10  6.25  10  10  6.25  74.75   
27  CR  MI  13  6.75  6.50  6.50  6.50  6.25  10  6.50  10  10  6.50  75.50   
28  CR  MI  14  6.50  7.00  6.50  6.50  6.50  10  6.50  10  10  6.50  76.00   
29  CR  MI  15  7.00  6.75  6.75  6.50  6.50  10  6.50  10  10  6.00  76.00   
30  CR  MI  15  7.00  6.25  6.25  6.00  6.25  10  6.25  10  10  6.25  74.25   
31  CR  MI  15  6.75  6.50  6.50  6.25  6.00  10  6.25  10  10  6.00  74.25   
32  CR  MI  15  6.75  6.50  6.50  6.25  6.25  10  6.25  10  10  6.25  74.75   
33  CR  MI  15  6.75  6.50  6.50  7.00  6.50  10  6.50  10  10  6.50  76.25   
34  CR  FL  15  6.50  6.75  6.50  7.00  6.50  10  6.50  10  10  6.50  76.25   
35  CR  FL  15  6.50  6.75  6.50  7.00  6.50  10  6.50  10  10  6.50  76.25   
36  CR  FL  15  6.50  6.50  6.25  6.25  6.50  10  6.50  10  10  6.50  75.00   
37  CR  FL  15  7.25  7.00  7.00  6.00  6.50  10  6.50  10  10  7.00  77.25   
38  CR  FL  15  6.75  6.50  6.00  6.25  6.75  10  6.50  10  10  6.50  75.25   
39  CR  FL  15  6.50  6.50  6.50  6.25  6.50  10  6.50  10  10  6.25  75.00   
40  CR  FL  15  7.00  6.75  6.50  6.00  7.00  10  6.50  10  10  6.50  76.25   
41  CR  FL  15  7.25  7.00  6.75  6.00  6.50  10  6.50  10  10  6.50  76.50   
42  CR  FL  16  6.50  6.25  6.25  6.00  6.25  10  6.50  10  10  6.50  74.25   
43  CR  FL  16  6.75  6.25  6.25  6.50  6.25  10  6.25  10  10  6.25  74.50   
44  CR  FL  16  6.75  6.50  6.50  6.75  6.50  10  6.50  10  10  6.50  76.00   
45  CR  FL  17  6.75  7.00  6.75  6.50  6.50  10  6.50  10  10  7.00  77.00   
46  CR  FL  17  6.75  6.50  6.25  6.25  6.25  10  6.50  10  10  6.50  75.00   
47  CR  FL  17  7.00  6.25  6.25  6.25  6.25  10  6.25  10  10  6.25  74.50   
48  OA  PE  13  7.00  6.50  6.50  6.50  6.00  10  6.00  10  10  6.00  74.50   
49  OA  MI  13  7.00  6.75  6.75  6.50  6.25  10  6.25

In [180]:
#List elements of cluster 2
df_nplus2 = display(list_with_clusters, 2)
df_nplus2

0   1   2     3     4     5     6     7   8     9   10  11    12     13  \
0   CO  PE  13  6.50  6.00  6.00  6.00  6.00  10  6.00  10  10  6.00  72.50   
1   CO  PE  13  6.00  6.00  6.00  6.00  6.00  10  6.00  10  10  6.00  72.00   
2   CO  PE  13  6.75  6.00  6.00  6.00  6.00  10  6.00  10  10  6.00  72.75   
3   CO  PE  13  6.75  6.50  6.50  6.00  6.00  10  6.00  10  10  6.00  73.75   
4   CO  MI  13  6.00  7.00  6.25  6.00  6.00  10  6.25  10  10  6.25  73.75   
..  ..  ..  ..   ...   ...   ...   ...   ...  ..   ...  ..  ..   ...    ...   
77  OA  FL  18  6.50  6.00  6.00  6.00  6.25  10  6.00  10  10  6.00  72.75   
78  OA  FL  18  6.00  6.00  6.00  6.00  6.00  10  6.00  10  10  6.25  72.25   
79  OA  FL  18  6.00  6.00  6.00  6.00  6.00  10  6.00  10  10  6.50  72.50   
80  OA  FL  18  6.25  6.25  6.25  6.00  6.25  10  6.00  10  10  6.25  73.25   
81  OA  FL  18  6.25  6.25  6.25  6.25  6.25  10  6.25  10  10  6.25  73.75   

    14  
0    2  
1    2  
2    2  
3    2  
4    2  
..  ..  
77   2  
78   2  
79   2  
80   2  
81   2  

[82 rows x 15 columns]