In [203]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.cluster import KMeans

#Tutorial can be found here: https://www.youtube.com/watch?v=CIfZi0niNE0

In [204]:
dataset = pd.read_csv('CoffeeBeansCleaned.csv')
dataset.drop(columns = ['Shape'])

Variety  Sieve  Aroma  Flavor  Aftertaste  Acidity  Body  Uniformity  \
0        CO     13   6.50    6.00        6.00     6.00  6.00          10   
1        CO     13   6.00    6.00        6.00     6.00  6.00          10   
2        CO     13   6.75    6.00        6.00     6.00  6.00          10   
3        CO     13   6.75    6.50        6.50     6.00  6.00          10   
4        CO     13   6.75    6.25        6.25     6.25  6.50          10   
..      ...    ...    ...     ...         ...      ...   ...         ...   
177      OA     18   6.50    6.00        6.00     6.00  6.25          10   
178      OA     18   6.00    6.00        6.00     6.00  6.00          10   
179      OA     18   6.00    6.00        6.00     6.00  6.00          10   
180      OA     18   6.25    6.25        6.25     6.00  6.25          10   
181      OA     18   6.25    6.25        6.25     6.25  6.25          10   

     Balance  clean cup  Sweetness  Taster score  Final score  
0       6.00         10         10          6.00        72.50  
1       6.00         10         10          6.00        72.00  
2       6.00         10         10          6.00        72.75  
3       6.00         10         10          6.00        73.75  
4       6.50         10         10          6.50        75.00  
..       ...        ...        ...           ...          ...  
177     6.00         10         10          6.00        72.75  
178     6.00         10         10          6.25        72.25  
179     6.00         10         10          6.50        72.50  
180     6.00         10         10          6.25        73.25  
181     6.25         10         10          6.25        73.75  

[182 rows x 13 columns]

In [205]:
X = dataset

In [206]:
ct = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[0,1])], remainder="passthrough")

In [192]:
X_train = np.array(ct.fit_transform(X))

In [209]:
#Clustering
km = KMeans(n_clusters = 3, init="k-means++", random_state=42)
y_means = km.fit(X_train)

In [210]:
y_means

KMeans(n_clusters=3, random_state=42)

In [211]:
#Centers
y_means.cluster_centers_

array([[1.77419355e-01, 3.87096774e-01, 4.35483871e-01, 1.00000000e+00,
        5.55111512e-17, 4.16333634e-17, 1.70161290e+01, 6.45580645e+00,
        6.18145161e+00, 6.11693548e+00, 6.10483871e+00, 6.12500000e+00,
        1.00000000e+01, 6.16532258e+00, 1.00000000e+01, 1.00000000e+01,
        6.18548387e+00, 7.33387097e+01],
       [3.91304348e-01, 3.69565217e-01, 2.39130435e-01, 4.56521739e-01,
        5.21739130e-01, 2.17391304e-02, 1.46086957e+01, 7.15760870e+00,
        7.02717391e+00, 6.94565217e+00, 7.03260870e+00, 6.94021739e+00,
        1.00000000e+01, 6.96195652e+00, 1.00000000e+01, 1.00000000e+01,
        7.07608696e+00, 7.91413043e+01],
       [4.72972973e-01, 2.83783784e-01, 2.43243243e-01, 4.32432432e-01,
        4.59459459e-01, 1.08108108e-01, 1.42567568e+01, 6.61824324e+00,
        6.41554054e+00, 6.28716216e+00, 6.25337838e+00, 6.25675676e+00,
        1.00000000e+01, 6.29729730e+00, 1.00000000e+01, 1.00000000e+01,
        6.31756757e+00, 7.43445946e+01]])

In [212]:
#Check where each record resides in which cluster
km.labels_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1,
       2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2,
       1, 2, 2, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 2,
       1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 0, 0, 0, 0,
       2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0])

In [213]:
#Count how many records are in each of the clusters
labels = km.labels_
clusterCount = np.bincount(labels)
clusterCount

array([62, 46, 74], dtype=int64)

In [220]:
#List the records in dataframe form
df_with_shape_column = pd.read_csv('CoffeeBeansCleaned.csv')

cluster = km.labels_
df_with_shape_column['cluster'] = cluster

df_with_shape_column

Variety Shape  Sieve  Aroma  Flavor  Aftertaste  Acidity  Body  \
0        CO    PE     13   6.50    6.00        6.00     6.00  6.00   
1        CO    PE     13   6.00    6.00        6.00     6.00  6.00   
2        CO    PE     13   6.75    6.00        6.00     6.00  6.00   
3        CO    PE     13   6.75    6.50        6.50     6.00  6.00   
4        CO    MI     13   6.75    6.25        6.25     6.25  6.50   
..      ...   ...    ...    ...     ...         ...      ...   ...   
177      OA    FL     18   6.50    6.00        6.00     6.00  6.25   
178      OA    FL     18   6.00    6.00        6.00     6.00  6.00   
179      OA    FL     18   6.00    6.00        6.00     6.00  6.00   
180      OA    FL     18   6.25    6.25        6.25     6.00  6.25   
181      OA    FL     18   6.25    6.25        6.25     6.25  6.25   

     Uniformity  Balance  clean cup  Sweetness  Taster score  Final score  \
0            10     6.00         10         10          6.00        72.50   
1            10     6.00         10         10          6.00        72.00   
2            10     6.00         10         10          6.00        72.75   
3            10     6.00         10         10          6.00        73.75   
4            10     6.50         10         10          6.50        75.00   
..          ...      ...        ...        ...           ...          ...   
177          10     6.00         10         10          6.00        72.75   
178          10     6.00         10         10          6.25        72.25   
179          10     6.00         10         10          6.50        72.50   
180          10     6.00         10         10          6.25        73.25   
181          10     6.25         10         10          6.25        73.75   

     cluster  
0          2  
1          2  
2          2  
3          2  
4          2  
..       ...  
177        0  
178        0  
179        0  
180        0  
181        0  

[182 rows x 15 columns]

In [221]:
#List the elements of cluster n method
def display(fullList, clusternum):
    new_list = []
    for x in list_with_clusters:
        for y in x:
            if x[14] == clusternum:
                new_list.append(x)
                break
    unique_df = pd.DataFrame(new_list)
    return unique_df

In [222]:
list_with_clusters = df_with_cluster_column.values.tolist()

#List elements of cluster 0
df_n = display(list_with_clusters, 0)
df_n

0   1   2     3     4     5     6     7   8     9   10  11    12     13  \
0   CO  FL  16  6.25  6.00  6.00  6.25  6.00  10  6.25  10  10  6.25  73.00   
1   CO  FL  16  6.00  6.00  6.25  6.00  6.00  10  6.00  10  10  6.50  72.75   
2   CO  FL  16  6.75  6.25  6.25  6.00  6.25  10  6.25  10  10  6.00  73.75   
3   CO  FL  16  7.50  6.25  6.00  6.00  6.25  10  6.25  10  10  6.25  74.50   
4   CO  FL  17  6.25  6.25  6.00  6.00  6.25  10  6.50  10  10  6.50  73.75   
..  ..  ..  ..   ...   ...   ...   ...   ...  ..   ...  ..  ..   ...    ...   
57  OA  FL  18  6.50  6.00  6.00  6.00  6.25  10  6.00  10  10  6.00  72.75   
58  OA  FL  18  6.00  6.00  6.00  6.00  6.00  10  6.00  10  10  6.25  72.25   
59  OA  FL  18  6.00  6.00  6.00  6.00  6.00  10  6.00  10  10  6.50  72.50   
60  OA  FL  18  6.25  6.25  6.25  6.00  6.25  10  6.00  10  10  6.25  73.25   
61  OA  FL  18  6.25  6.25  6.25  6.25  6.25  10  6.25  10  10  6.25  73.75   

    14  
0    0  
1    0  
2    0  
3    0  
4    0  
..  ..  
57   0  
58   0  
59   0  
60   0  
61   0  

[62 rows x 15 columns]

In [223]:
#List elements of cluster 1
df_nplus1 = display(list_with_clusters, 1)
df_nplus1

0   1   2     3     4     5     6     7   8     9   10  11    12     13  \
0   CO  MI  14  7.00  7.00  7.25  7.25  7.00  10  7.00  10  10  7.25  79.75   
1   CO  MI  14  7.75  7.25  7.25  7.25  7.00  10  7.00  10  10  7.25  80.75   
2   CO  MI  14  7.50  7.00  7.00  7.00  6.50  10  7.25  10  10  7.25  79.50   
3   CO  MI  15  7.00  7.00  7.00  6.75  7.00  10  6.75  10  10  6.75  78.25   
4   CO  MI  15  7.25  7.25  7.00  7.00  6.75  10  7.25  10  10  7.00  79.50   
5   CO  FL  13  7.00  7.00  7.00  7.25  7.00  10  7.00  10  10  7.00  79.25   
6   CO  FL  13  7.50  7.25  7.50  7.25  7.25  10  7.25  10  10  7.25  81.25   
7   CO  FL  13  7.00  7.00  7.00  7.00  6.50  10  7.00  10  10  7.00  78.50   
8   CO  FL  13  7.25  6.50  6.50  7.00  6.75  10  6.50  10  10  6.50  77.00   
9   CO  FL  13  7.25  6.50  6.50  7.00  6.75  10  6.50  10  10  6.50  77.00   
10  CO  FL  16  7.00  7.25  7.25  7.25  7.25  10  7.25  10  10  7.50  80.75   
11  CO  FL  16  7.25  7.25  6.75  7.00  7.00  10  6.50  10  10  6.75  78.50   
12  CO  FL  16  7.00  6.75  6.25  7.00  6.50  10  6.75  10  10  7.25  77.50   
13  CO  FL  16  7.50  7.75  7.00  7.00  7.00  10  7.00  10  10  7.00  80.25   
14  CO  FL  17  7.50  7.25  7.50  7.50  7.00  10  7.25  10  10  7.25  81.25   
15  CO  FL  17  7.50  7.25  7.25  7.25  7.25  10  7.25  10  10  7.25  81.00   
16  CO  FL  18  7.00  7.25  7.00  7.75  7.25  10  7.00  10  10  7.25  80.50   
17  CO  FL  18  7.00  7.00  7.00  7.25  7.00  10  7.00  10  10  7.25  79.50   
18  CR  MI  13  7.00  7.25  7.25  7.25  7.25  10  7.25  10  10  7.25  80.50   
19  CR  MI  13  6.75  6.75  6.75  6.75  6.75  10  6.75  10  10  7.00  77.50   
20  CR  MI  13  7.25  7.50  7.50  7.00  7.00  10  7.25  10  10  7.25  80.75   
21  CR  MI  13  7.50  7.25  6.25  6.25  6.50  10  7.00  10  10  7.00  77.75   
22  CR  MI  13  6.50  7.00  7.00  6.75  6.75  10  6.75  10  10  7.00  77.75   
23  CR  MI  14  7.25  7.00  7.00  7.25  7.25  10  7.00  10  10  7.00  79.75   
24  CR  MI  14  7.00  7.25  7.25  7.25  7.00  10  7.25  10  10  7.25  80.25   
25  CR  MI  14  7.00  7.25  7.00  7.25  7.25  10  7.25  10  10  7.50  80.50   
26  CR  MI  14  7.75  7.00  6.50  6.75  6.50  10  7.00  10  10  7.00  78.50   
27  CR  MI  14  7.00  7.00  7.25  7.25  7.25  10  7.00  10  10  7.00  79.75   
28  CR  MI  14  7.00  6.75  6.75  6.50  7.00  10  6.50  10  10  7.00  77.50   
29  CR  MI  15  7.25  7.00  7.00  7.00  6.50  10  7.00  10  10  7.00  78.75   
30  CR  MI  15  7.50  7.00  7.00  7.25  7.00  10  7.00  10  10  7.00  79.75   
31  CR  MI  15  7.25  6.50  6.50  7.00  6.25  10  7.00  10  10  7.00  77.50   
32  CR  MI  15  7.50  7.00  7.00  7.00  7.00  10  7.00  10  10  7.00  79.50   
33  CR  FL  15  7.25  7.00  7.00  6.00  6.50  10  6.50  10  10  7.00  77.25   
34  CR  FL  17  6.75  7.00  6.75  6.50  6.50  10  6.50  10  10  7.00  77.00   
35  OA  PE  13  7.00  7.00  7.00  7.00  7.00  10  7.00  10  10  7.00  79.00   
36  OA  MI  13  7.00  7.25  6.75  7.25  7.25  10  7.00  10  10  7.50  80.00   
37  OA  MI  13  7.00  7.00  7.00  7.25  7.00  10  7.00  10  10  7.00  79.25   
38  OA  MI  13  7.00  6.50  6.50  6.50  7.00  10  7.00  10  10  7.00  77.50   
39  OA  MI  14  7.00  7.00  7.00  7.25  7.25  10  7.00  10  10  7.25  79.75   
40  OA  FL  13  7.00  7.00  7.00  7.25  7.25  10  7.00  10  10  7.25  79.75   
41  OA  FL  13  7.25  6.50  6.50  7.25  7.25  10  6.75  10  10  7.00  78.50   
42  OA  FL  16  7.00  7.00  7.00  7.00  7.00  10  7.00  10  10  7.00  79.00   
43  OA  FL  17  7.00  7.00  7.00  7.00  7.00  10  7.00  10  10  7.00  79.00   
44  OA  FL  17  7.00  7.00  7.00  7.00  7.00  10  7.00  10  10  7.00  79.00   
45  OA  FL  18  7.25  7.00  7.00  7.00  7.25  10  7.00  10  10  7.00  79.50   

    14  
0    1  
1    1  
2    1  
3    1  
4    1  
5    1  
6    1  
7    1  
8    1  
9    1  
10   1  
11   1  
12   1  
13   1  
14   1  
15   1  
16   1  
17   1  
18   1  
19   1  
20   1  
21   1  
22   1  
23   1  
24   1  
25   1  
26   1  
27   1  
28   1  
29   1  
30   1  
31

In [224]:
#List elements of cluster 2
df_nplus2 = display(list_with_clusters, 2)
df_nplus2

0   1   2     3     4     5     6     7   8     9   10  11   12     13  14
0   CO  PE  13  6.50  6.00  6.00  6.00  6.00  10  6.00  10  10  6.0  72.50   2
1   CO  PE  13  6.00  6.00  6.00  6.00  6.00  10  6.00  10  10  6.0  72.00   2
2   CO  PE  13  6.75  6.00  6.00  6.00  6.00  10  6.00  10  10  6.0  72.75   2
3   CO  PE  13  6.75  6.50  6.50  6.00  6.00  10  6.00  10  10  6.0  73.75   2
4   CO  MI  13  6.75  6.25  6.25  6.25  6.50  10  6.50  10  10  6.5  75.00   2
..  ..  ..  ..   ...   ...   ...   ...   ...  ..   ...  ..  ..  ...    ...  ..
69  OA  FL  13  6.50  6.50  6.50  6.50  6.25  10  6.50  10  10  6.5  75.25   2
70  OA  FL  13  6.25  6.25  6.00  6.00  6.00  10  6.00  10  10  7.0  72.50   2
71  OA  FL  14  7.00  6.00  6.00  7.00  7.00  10  7.00  10  10  7.0  72.00   2
72  OA  FL  14  6.50  6.75  6.25  6.50  6.75  10  6.50  10  10  6.5  74.75   2
73  OA  FL  16  7.00  6.50  6.50  6.25  6.25  10  6.25  10  10  6.5  75.25   2

[74 rows x 15 columns]